POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@j.com"
}

###
### jane id 5c3eabaa-94e0-4fe5-a043-b7fc9c4a36d1
### john id 2dfb350a-72a5-4596-aba2-03e247220caf

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "e21b3597-dddb-4dd2-a645-82c9c11e7787"
}

### account Jane: 84b29a03-d5a6-429a-b466-36f82db8e427
### account John: 42b7e74c-4da7-4b85-a127-19e1f1e410f6

###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "84b29a03-d5a6-429a-b466-36f82db8e427",
    "account_id_to": "42b7e74c-4da7-4b85-a127-19e1f1e410f6",
    "amount": 50
}
