version: '3'
services:
  mysql:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: wallet
      MYSQL_PASSWORD: 1234
    ports:
      - 3306:3306
    volumes:
      - .docker/mysql:/var/lib/mysql
  mygoapp:
    build: .
    container_name: mygoapp
    ports:
      - "8080:8080"
